INSERT INTO genre(name) VALUES("adventure");
INSERT INTO genre(name) VALUES("comedy");
INSERT INTO genre(name) VALUES("family");
INSERT INTO genre(name) VALUES("fantasy");
INSERT INTO genre(name) VALUES("action");
INSERT INTO genre(name) VALUES("sci-fi");
INSERT INTO genre(name) VALUES("Animation");
INSERT INTO genre(name) VALUES("mystery");
INSERT INTO genre(name) VALUES("thriller");